EasyKayzey/CASprzak

src/functions/commutative/CommutativeFunction.java
src/functions/commutative/Product.java
src/functions/commutative/Sum.java
src/functions/unitary/transforms/Differential.java
src/functions/unitary/transforms/Integral.java
src/functions/unitary/transforms/TransformFunction.java
src/parsing/FunctionMaker.java
src/parsing/InfixTokenizer.java
src/parsing/KeywordInterface.java
src/parsing/OperationLists.java
tests/DifferentialTest.java

This branch solves the problems of null integrals and products of integrals by adding a few simplification steps:
Let `\int(function)d0` be an integral with respect to `null`, `\int(function)dv` be an integral with respect to `v`, and `\d(v)` be a differential with respect to `v`:
1. Simplifies expressions of the form `something * \int(function)d0 * \d(v)` to `something * \int(function)dv`
2. Simplifies expressions of the form `\int(function * \d(v))d0` to `\int(function)dv`

Fix null integral problems

---

tests/LatexTest.java
tests/NoEscapeTest.java
tests/SimplifyTest.java

Creates a new test category for all things that are explicitly without LaTeX escapes, and escapes all other tests

Add NoEscapeTest and make all other tests escaped

---

src/parsing/FunctionParser.java
src/ui/CommandUI.java

This branch:
- rewrites most parser errors
- makes it so that stack pops are checked before execution so that an exception is preemptively thrown
- makes it so that parser errors are not immediately fed to the user and must be printed with `_`

Make parsing errors more descriptive

---

src/functions/commutative/CommutativeFunction.java
src/functions/commutative/Product.java
src/functions/commutative/Sum.java

Makes getIdentityValue and operate of CommutativeFunction be abstract methods rather than instance variables

CommutativeFunction abstract operations

---

src/parsing/KeywordInterface.java
src/tools/MiscTools.java

This branch:
- Removes an unnecessary ternary operator in the evaluation of GCD through MiscTools
- Remove whitespace in the KeywordInterface private constructor

GCD evaluation efficiency

---

ChangeLog.md
src/functions/GeneralFunction.java
src/functions/binary/Logb.java
src/functions/binary/Pow.java
src/functions/commutative/CommutativeFunction.java
src/functions/unitary/specialcases/Ln.java
src/functions/unitary/transforms/Differential.java
src/functions/unitary/transforms/Integral.java
src/functions/unitary/transforms/PartialDerivative.java
src/parsing/OperationMaps.java
src/tools/ArrayTools.java
src/tools/integration/StageOne.java
tests/EqualsTest.java
tests/IntegerTest.java
tests/IntegralTest.java
tests/KeywordInterfaceTest.java
tests/NoEscapeTest.java
tests/SimplifyTest.java

The current implementation of `equals` is misleading as it checks if two functions are equivalent, not equal. This branch remedies this by renaming the current implementation of `equals` to `equalsSimplified`. In addition, this branch:
- Fixes a bad simplification in `Ln.simplifyInverse`
- Implements ArrayTools.equalsSimplified

Change equals to equalsSimplified

---

ChangeLog.md
src/functions/binary/integer/IntegerBinaryFunction.java
src/tools/ParsingTools.java

Fixes:
- Error in `IntegerBinaryFunctions` using incorrect classname
- Bad rounding in `ParsingTools.toInteger` and `ParsingTools.isAlmostInteger`
This time, without the extra stuff that wasn't supposed to be pushed.

Integer function errors 2

---

ChangeLog.md
src/functions/GeneralFunction.java
src/functions/unitary/transforms/Differential.java
src/functions/unitary/transforms/Integral.java
src/functions/unitary/transforms/PartialDerivative.java
src/parsing/KeywordInterface.java
tests/KeywordInterfaceTest.java
tests/SubstituteTest.java

Makes `sub` more powerful by allowing the substitution of multiple variables at once, like the old `setv` function, and makes the internal substituteVariable method use a `Map<String, GeneralFunction>`.

Make KeywordInterface substitute more powerful and fix setVariables removal

---

src/functions/commutative/CommutativeFunction.java
src/functions/commutative/Product.java
src/functions/commutative/Sum.java
src/functions/commutative/integer/IntegerCommutativeFunction.java

Makes the overriding collectors for joining toStrings in commutative functions static

Make default joining collectors static

---

ChangeLog.md
src/parsing/LatexReplacer.java
tests/LatexTest.java
tests/NoEscapeTest.java

Removes a space in the general regex of LatexReplacer to fix expressions like `1 + sin(x)` that have spaces.

Fix broken LaTeX escapes

---

ChangeLog.md
src/functions/special/Constant.java
src/parsing/KeywordInterface.java
src/ui/CommandUI.java

- Add a 'version' command
- Add a 'reset' command
- Fix 'defconstant' not latex escaping the constant name
- Throw an error when attempting to use nested quotes

Keyword interface improvements 1

---

src/config/Settings.java
src/config/cas.properties
src/functions/special/Constant.java
src/functions/special/Variable.java
tests/KeywordInterfaceTest.java

Moves the removal of escapes in the case of `removeEscapes` from the creation of variables/constants to their printing

Move escape processing

---

src/parsing/KeywordInterface.java

Fixes splitting of expressions like `eval "sa f" x=2` where `f` is a defined function in terms of `x`

Fix quotes splitting in eval

---

src/parsing/InfixTokenizer.java
tests/FunctionTest.java

Fixes expressions like `1/.2` where division occurs with a non-leading-zero decimal

Division by decimals

---

CHANGELOG.md
src/parsing/KeywordInterface.java

- Fix malformed whitespace in the `help` command
- Add 'v' to the version String from the `version` command
- Add `v` as another way to call `version` in KeywordInterface
- Add a period to the end of 'Reset done.'

Keyword interface touchup

---

tests/KeywordInterfaceTest.java

- Fix `useKeywords` returning GeneralFunctions and breaking tests in KeywordInterfaceTest

Fix KeywordInterfaceTest

---

CHANGELOG.md
src/parsing/InfixTokenizer.java
src/parsing/LatexReplacer.java
tests/LatexTest.java

Fixes:
- Inputs like `sinner` being escaped to the variable `\sinner` rather than `s*i*n*n*e*r`
- Logb parsing failing on edge cases

Fix broken LaTeX escaping

---

README.md

This PR adds some basic instructions to the README for building and testing with Gradle.

Add basic Gradle instructions to README

---

README.md

This PR adds instructions for running the command UI directly from Gradle to the README.

Add Gradle run instructions to README

---

CHANGELOG.md
commandui/src/java/show/ezkz/casprzak/commandui/CASDemo.java
core/src/java/show/ezkz/casprzak/core/config/Settings.java
core/src/java/show/ezkz/casprzak/core/config/cas.properties
core/src/java/show/ezkz/casprzak/core/tools/ParsingTools.java
parsing/src/java/show/ezkz/casprzak/parsing/FunctionParser.java
parsing/src/java/show/ezkz/casprzak/parsing/LatexReplacer.java
tests/NoEscapeTest.java

- Fix 'enforceEscapes' not being a setting
- Fix inconsistent variable names in the tutorial
- Fix the CAS automatically simplifying expressions in the simplify section

Tutorial fixes

---

core/src/java/show/ezkz/casprzak/core/functions/endpoint/Constant.java

Ensures the argument of getSpecialConstant is a special constant to prevent a NullPointerException

Add null check in getSpecialConstant

---

CHANGELOG.md
commandui/src/java/show/ezkz/casprzak/commandui/KeywordInterface.java

Fixes bug where errors are not reset when `reset` is called

Make KeywordInterface reset method reset stored error

---

core/src/java/show/ezkz/casprzak/core/tools/ParsingTools.java
tests/MiscTest.java

Removes non-printable characters and whitespace from allowable name regex

Fix whitespace variables
