.idea/inspectionProfiles/Project_Default.xml
src/functions/special/Constant.java
src/parsing/KeywordInterface.java
src/tools/singlevariable/Extrema.java

Refactor Constant to use a HashMap instead of ConstantIDs. This should serve as a template for eventually refactoring Variable to use the same system.

Refactor of Constant IDs

---

src/functions/Function.java
src/functions/binary/BinaryFunction.java
src/functions/commutative/CommutativeFunction.java
src/functions/special/SpecialFunction.java
src/functions/unitary/UnitaryFunction.java
src/tools/SearchTools.java
tests/IteratorTest.java

Makes Function implement Iterable<Function> and writes the implementation to support it

Make Functions iterable

---

README.md

Adds information about `cas.properties` and release binaries to the README.

Update README.md with config and binary info

---

ChangeLog.md
src/functions/binary/BinaryFunction.java
src/functions/binary/Rand.java
src/functions/binary/integer/IntegerBinaryFunction.java
src/functions/commutative/integer/GCD.java
src/functions/commutative/integer/IntegerCommutativeFunction.java
src/functions/commutative/integer/LCM.java
src/functions/unitary/integer/IntegerUnitaryFunction.java
src/functions/unitary/integer/combo/Factorial.java
src/functions/unitary/integer/combo/RFactorial.java
src/functions/unitary/integer/combo/SFactorial.java
src/functions/unitary/piecewise/Ceil.java
src/functions/unitary/piecewise/Floor.java
src/functions/unitary/piecewise/PiecewiseFunction.java
src/functions/unitary/piecewise/Round.java
src/functions/unitary/specialcases/SpecialCaseBinaryFunction.java
src/tools/MiscTools.java
tests/IntegerTest.java
tests/MiscTest.java

Add lcm, gcd, floor, ceil, round, and rand operations
Add abstract classes for the new integer operations
Create a new test class for integer operations

Integer operations 2

---

.idea/inspectionProfiles/Project_Default.xml
src/functions/binary/Logb.java
src/functions/binary/Pow.java
src/functions/commutative/Product.java
src/functions/unitary/UnitaryFunction.java
src/functions/unitary/transforms/Integral.java
src/parsing/KeywordInterface.java
src/tools/ParsingTools.java
src/ui/CommandUI.java

Currently, these warnings are suppressed manually almost always everywhere, This branch suppresses the warnings globally and removes the manual suppressions.

Suppress ChainOfInstanceofChecks warnings

---

ChangeLog.md
src/functions/binary/Rand.java
src/functions/binary/integer/IntegerBinaryFunction.java
src/functions/commutative/integer/IntegerCommutativeFunction.java
src/functions/unitary/integer/IntegerUnitaryFunction.java
src/functions/unitary/integer/combo/RFactorial.java
src/functions/unitary/piecewise/Ceil.java
src/functions/unitary/piecewise/Dirac.java
src/functions/unitary/piecewise/Floor.java
src/functions/unitary/piecewise/Round.java
src/functions/unitary/transforms/Differential.java
src/tools/exceptions/DerivativeDoesNotExistException.java
src/tools/exceptions/IntegrationFailedException.java
src/tools/integration/StageOne.java

- Create the DerivativeDoesNotExistException
- Implement in functions who don't have derivatives

Derivative exception

---

src/functions/commutative/integer/GCD.java
src/functions/commutative/integer/IntegerCommutativeFunction.java
src/functions/commutative/integer/LCM.java

- Make the toString for IntegerCommutatativeFunctions be in IntegerCommutativeFunction

Integer commutative function to string

---

.gitignore

Add discord.xml to gitignore

---

src/functions/GeneralFunction.java
src/functions/binary/BinaryFunction.java
src/functions/commutative/CommutativeFunction.java
src/functions/special/Constant.java
src/functions/special/Variable.java
src/functions/unitary/UnitaryFunction.java
tests/MiscTest.java

This branch implements `hashCode` to fulfill the contract specified by `Object`.

Implement `hashCode`

---

src/parsing/FunctionParser.java

Makes parsing errors more descriptive

Make parsing errors more descriptive

---

src/config/Settings.java
src/config/SettingsParser.java
src/config/cas.properties
src/parsing/InfixTokenizer.java

Allows for the maximum length of an escaped string to be changed in the config.

Add Settings.maxEscapeLength

---

src/parsing/FunctionParser.java

Adds error handling for mismatched parentheses in parsing, and prevents parentheses from being added to postfix stack.

Parenthesis errors

---

src/parsing/FunctionParser.java

Adds a check to ensure stack does not run out of tokens while parsing parentheses

Improve parenthesis error handling

---

ChangeLog.md
src/parsing/InfixTokenizer.java
src/parsing/OperationMaps.java
tests/DifferentialTest.java
tests/FunctionTest.java
tests/IntegralTest.java

- Add parsing for Round in OperationMaps
- Fix parsing of Dirac from turning into a differential
- Fix parsing of integer division

Function parsing 1

---

src/parsing/OperationMaps.java
src/tools/DefaultFunctions.java

-Implement frac, choose, permute, and logbase10 in DefaultFunctions
-Make the corresponding operations in OperationMaps use DefaultFunctions

Default functions 1

---

src/functions/unitary/transforms/Differential.java
src/parsing/OperationMaps.java

Lambda-ize some things in OperationMaps and create new Differential constructor

Lambda-ize OperationMaps

---

src/parsing/OperationMaps.java

Fix typo in documentation

---

src/ui/CASDemo.java

Fix substitutions in CASDemo with the new substitute method.

Make CASDemo use the new sub method

---

ChangeLog.md
src/functions/GeneralFunction.java
src/functions/unitary/transforms/Integral.java
src/parsing/FunctionParser.java
src/parsing/KeywordInterface.java
src/tools/IntegralTools.java
src/tools/MiscTools.java
src/tools/integration/StageOne.java
src/ui/CASDemo.java

Make def and sub in CommandUI now automatically perform a minimalSimplify

Substitute keyword 1

---

src/functions/commutative/CommutativeFunction.java
src/functions/commutative/Product.java
src/functions/commutative/Sum.java
src/functions/commutative/integer/IntegerCommutativeFunction.java

Modularizes CommutativeFunction toStrings using collectors and adds a single method for child classes to support

Make CommutativeFunction toStrings use streams

---

src/parsing/InfixTokenizer.java

Switch from splitAsStream to List.of

Make tokenizeInfix use List.of

---

README.md

Updates to new Easykayzey addresses

Fix emails in README

---

ChangeLog.md
src/parsing/KeywordInterface.java

Adds array indexing to the KeywordInterface and adds `_` support to `eval`

Add array indexing

---

src/functions/binary/BinaryFunction.java
src/functions/unitary/UnitaryFunction.java
src/parsing/KeywordInterface.java
src/tools/PolynomialTools.java
tests/ComboTest.java
tests/DifferentialTest.java
tests/FunctionTest.java
tests/LatexTest.java

Replaces all evaluate(null) in the code

Replace all evaluate(null) with evaluate(Map.of())

---

src/parsing/KeywordInterface.java
src/tools/exceptions/UserExitException.java
src/ui/CASDemo.java
src/ui/CommandUI.java
tests/DerivativeTest.java
tests/KeywordInterfaceTest.java

Completely rewrites all exit logic by introducing a new exception to replace convoluted and repeated exit checks

Rework exit logic

---

src/ui/CommandUI.java

Refactor name of CommandUI scanner for consistency and make an if statement one line

Refactor name of CommandUI scanner 

---

src/functions/binary/BinaryFunction.java
src/functions/binary/Pow.java
src/functions/commutative/CommutativeFunction.java
src/tools/PolynomialTools.java

- Improves exception messages which had the term "should never run"

Should never run exceptions

---

src/config/Settings.java
src/config/SettingsParser.java
src/config/cas.properties
src/parsing/InfixTokenizer.java
src/parsing/OperationMaps.java

Adds setting to disable combinatorics to, for example, enable C and P to be used as variables

Add combinatoric parsing setting

---

ChangeLog.md
src/parsing/KeywordInterface.java
src/tools/exceptions/CommandNotFoundException.java
src/ui/CommandUI.java

Adds exception cause to `CommandNotFoundException` while improving user-end error handling

Exception Cause

---

src/parsing/KeywordInterface.java
src/tools/ParsingTools.java
src/ui/CASDemo.java
src/ui/CommandUI.java

Switch many methods to use nextLine() rather than next(), and change `newline` regex to use `\R`

Newline Removal

---

src/config/Settings.java
src/config/cas.properties
src/functions/special/Constant.java
src/functions/special/Variable.java
src/parsing/KeywordInterface.java
src/tools/ParsingTools.java

Makes alphanumerics enforcement optional

Alphanumeric Setting

---

src/parsing/KeywordInterface.java

- Change version String in KeywordInterface

Change version String

---

CODE_OF_CONDUCT.md
README.md
src/config/Settings.java

Updates README and CODE-OF-CONDUCT for 0.2.1 and fixes `maxEscapeLength` documentation

Update README, CODE-OF-CONDUCT, and fix documentation

---

src/output/OutputFunction.java

- Add documentation for equals and hashCode

Output function documentation

---

CHANGELOG.md

Fixes subsections in CHANGELOG.md

Fix subsections in CHANGELOG.md

---

src/parsing/KeywordInterface.java

Ports KeywordInterface to always output a Constant rather than a Double

Constant Output

---

src/functions/GeneralFunction.java
src/functions/binary/BinaryFunction.java
src/functions/binary/Pow.java
src/functions/unitary/UnitaryFunction.java
src/parsing/KeywordInterface.java
src/tools/ParsingTools.java
src/tools/PolynomialTools.java
tests/ComboTest.java
tests/DifferentialTest.java
tests/FunctionTest.java
tests/IntegerTest.java
tests/LatexTest.java

Creates a no-argument evaluation method passing in an empty map as input

Create no-argument evaluation method

---

CHANGELOG.md
src/functions/unitary/transforms/Differential.java

- Fix `Differentials` being made with null operands, causing `NullPointerException`s

Fix null differential

---

.github/workflows/gradle.yml

This PR adds a GitHub Actions workflow to automatically build and test each commit or pull request on `master`.

Add GitHub Actions for Gradle

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Update emails in `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` to the 'ezkz' domain

Update emails to the ezkz domain.

---

core/src/java/show/ezkz/casprzak/core/tools/integration/StageOne.java

- Add on-demand importing to StageOne

Add on-demand importing to StageOne

---

core/src/java/show/ezkz/casprzak/core/functions/binary/Logb.java
core/src/java/show/ezkz/casprzak/core/functions/binary/Pow.java
core/src/java/show/ezkz/casprzak/core/functions/unitary/specialcases/Exp.java
core/src/java/show/ezkz/casprzak/core/functions/unitary/specialcases/Ln.java
core/src/java/show/ezkz/casprzak/core/tools/helperclasses/LogInterface.java
core/src/java/show/ezkz/casprzak/core/tools/helperclasses/PowInterface.java

To be used to make simplification steps more general

Create and implement LogInterface and PowInterface

---

core/src/java/show/ezkz/casprzak/core/functions/endpoint/Constant.java

Instead of having the defaults in two different places, there is now a map that contains them.

Create and implement defaultSpecialConstants

---

CHANGELOG.md
commandui/src/java/show/ezkz/casprzak/commandui/KeywordInterface.java
core/src/java/show/ezkz/casprzak/core/config/Settings.java
core/src/java/show/ezkz/casprzak/core/config/cas.properties
core/src/java/show/ezkz/casprzak/core/tools/functiongenerators/HermitePolynomial.java
core/src/java/show/ezkz/casprzak/core/tools/functiongenerators/LaguerrePolynomial.java
core/src/java/show/ezkz/casprzak/core/tools/functiongenerators/LegrendePolynomial.java
core/src/java/show/ezkz/casprzak/core/tools/functiongenerators/TaylorSeries.java
tests/PolynomialTest.java

- Add Legrende, Hermite, and Laguerre polynomials
- Fix Taylor series returning degree-1 polynomials
- Allow Taylor series to use arbitrary variables

Improve TaylorSeries and add Legrende, Hermite, and Laguerre polynomials

---

README.md

Add calculus to readme

---

src/core/config/Settings.java

Fix properties separator
